name: bluebuild
on:
  schedule:
    - cron: "00 17 * * *" # build daily at 17:00 UTC (20 min after uBlue's own builds)
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch: # allows manually triggering a build from the Actions tab

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
